### PR TITLE
Add streaming API

### LINKED ISSUE #4: consider streaming api
I have a problem with a tbz that doesn't fit into memory, hence it would need to be decompressed in a streaming manner. do you have plans to support this?

### PR DESCRIPTION
**Pull request by kevva**
Fixes #4.

### CODE REVIEW

**Comment by juliangruber** [comment]
i think this is an improvement api wise, but doesn't fix the problem where an archive is very very big, it still all has to fit into memory

**Comment by kevva** [comment]
Not super familiar with how the internals of streams works outside of the API, but wouldn't this work:

```js
const extract = decompressTarbz2()(fs.createReadStream('archive.tar.bz2'));

extract.on('entry', (header, stream) => {
	stream.pipe(fs.createWriteStream(header.name));
});

extract.on('end', () => {
	console.log('done');
});
```

**Comment by juliangruber** [comment]
yeah that looks like it would work :)

**Comment by kevva** [comment]
Good :). I'm going to add that logic to `decompress` too so you would be able to supply a stream there and it'll do the writing for you (keeping the stats etc too).

**Pull request merged**
